<?php

namespace AppBundle\Repository;

/**
 * OptionTissuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionTissuRepository extends \Doctrine\ORM\EntityRepository
{
	
}
