<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * TissuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TissuRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Tissu p ORDER BY p.name ASC'
            )
            ->getResult();
    }
}
