# src/AppBundle/Resources/config/doctrine/Couleur.orm.yml
AppBundle\Entity\Couleur:
    type: entity
    table: couleur
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        htmlvalue:
            type: string
            length: 40
    manyToMany:
        tissu:
            targetEntity: Tissu
            mappedBy: couleur
            
