# src/AppBundle/Resources/config/doctrine/Tissu.orm.yml
AppBundle\Entity\Tissu:
    type: entity
    table: tissu
    id: 
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 200
        picturepath:
            type: string
            length: 50
    manyToMany:
        product:
            targetEntity: Product
            mappedBy: tissu   
        couleur:
            targetEntity: Couleur
            inversedBy: tissu
            joinTable:
                name: couleur_tissu
                joinColumns:
                    product_id:
                        referencedColumnName: id
                inverseJoinColumn:
                    couleur_id:
                        referencedColumnName: id
    oneToMany:
        optiontissu:
            targetEntity: OptionTissu
            mappedBy: tissu
        